### ISSUE TITLE
PHP deprecation notices

### ISSUE THREAD

**Issue by dregad** [raspopov/MantisLdapAvatar#2]
Testing this for mantisbt/mantisbt#2053:

DEPRECATED: 'Implicit conversion from float 78.0295566502463 to int loses precision' in ./MantisLdapAvatar.php' line 153
DEPRECATED: 'Implicit conversion from float 78.0295566502463 to int loses precision' in './MantisLdapAvatar.php' line 154

PHP 8.2.26

**Comment by raspopov** [comment]
Thank you very much. But it's strange that I didn't see this message although I'm sure my PHP has E_ALL (no E_DEPRECATED).

**Comment by dregad** [comment]
> my PHP has E_ALL (no E_DEPRECATED).

MantisBT has its own setting to control what and how errors are displayed - check *$g_display_errors*. The default setting will only display MantisBT fatal errors, suppressing output of all other error types. For development, I recommend
```php
$g_display_errors = array(
     E_WARNING           => DISPLAY_ERROR_HALT,
     E_ALL               => DISPLAY_ERROR_INLINE,
 );
 ```

**Comment by raspopov** [comment]
> check $g_display_errors

Thanks for the reminder, I had already used that setting in my config files, but it seems the particular server that has ActiveDirectory and where the plugin was tested was without it... 🤔
