### ISSUE TITLE
Warn if an invalid LDAP attribute has been entered

### ISSUE THREAD

**Issue by dregad** [raspopov/MantisLdapAvatar#3]
This is a convenience for the administrator.

Otherwise, the retrieval from LDAP silently fails (ldap_get_field_from_username returns *null*) and the admin will have to set $g_log_level = LOG_LDAP to find an entry in the log file like this:

2024-12-26 18:50:13 CET LDAP ldap_api.php:297 ldap_cache_user_data() WARNING: field 'xxx' does not exist

**Comment by raspopov** [comment]
By the way, this is a common case. If a user does not have an avatar in the database, then there is no attribute, even if it is named correctly.

**Comment by dregad** [comment]
This is the reason why the LDAP API squelches the warning.
